import Head from "next/head";
import {Navbar, Col , Container, Row , Tab, Nav } from "react-bootstrap";
import 'bootstrap/dist/css/bootstrap.min.css';
import React, { useState } from 'react';

const Dashboard = () => {

    return (
        <>
            <Head>
                <title>Admin panel</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Navbar bg="dark" variant="dark">
                <Container >
                    <Navbar.Brand href="/admin-panel/Dashboard">
                        <img alt="" src="/logo/admin-logo.png" width="100" height="100" className="d-inline-block align-top"/> {' '}
                    </Navbar.Brand>

                    <Navbar.Collapse className="justify-content-end">
                        <Navbar.Text>
                            <a href="http://localhost:8080/logout">Выйти</a>
                        </Navbar.Text>
                    </Navbar.Collapse>

                </Container>
            </Navbar>
            <Tab.Container id="left-tabs-example" defaultActiveKey="first">
                <Row>
                    <Col sm={2}>
                        <Nav variant="pills" className="flex-column">
                            <Nav.Item>
                                <Nav.Link eventKey="first">Дашборд</Nav.Link>
                            </Nav.Item>
                            <Nav.Item>
                                <Nav.Link eventKey="second">Пользователи</Nav.Link>
                            </Nav.Item>
                        </Nav>
                    </Col>
                    <Col sm={10}>
                        <Tab.Content>
                            <Tab.Pane eventKey="first">
                                <h1>Добро пожаловать</h1>
                            </Tab.Pane>
                            <Tab.Pane eventKey="second">
                                <h1>Тут можно добавить пользователей</h1>
                                As a decrepit father takes delight To see his active child do deeds of youth, So I, made lame by dearest spite,
                                Take all my comfort of thy worth and truth; For whether beauty, birth, or wealth, or wit,
                                Or any of these all, or all, or more, Entitled in thy parts, do crowned sit, I make my love engrafted, to this store: So then I am not
                                lame, poor, nor Whilst that this shadow doth such substance give

                                As a decrepit father takes delight To see his active child do deeds of youth, So I, made lame by dearest spite,
                                Take all my comfort of thy worth and truth; For whether beauty, birth, or wealth, or wit,
                                Or any of these all, or all, or more, Entitled in thy parts, do crowned sit, I make my love engrafted, to this store: So then I am not
                                lame, poor, nor Whilst that this shadow doth such substance give
                            </Tab.Pane>
                        </Tab.Content>
                    </Col>
                </Row>
            </Tab.Container>
        </>
    )
}


export default Dashboard;
