import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from "@/components/Header";
import MainContent from "@/components/MainContent";
import FollowUs from "@/components/FollowUs";
import OurMission from "@/components/OurMission";
import Features from "@/components/Features";

export default function Home() {

    const headerMenu = ['Главная','Функции','Наша миссия','О нас','Часы']

  return (
    <>
      <Head>
        <title>VOLUMENZEIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='pt-[14px]'>
          <Header/>
          <FollowUs/>
          <MainContent/>
          <Features/>
          <OurMission/>
      </main>
    </>
  )
}
