import Head from 'next/head'
import MainContent from "@/../../../../WebstormProjects/Trade-frontend/components/MainContent";
import FollowUs from "@/../../../../WebstormProjects/Trade-frontend/components/FollowUs";
import OurMission from "@/../../../../WebstormProjects/Trade-frontend/components/OurMission";
import Features from "@/../../../../WebstormProjects/Trade-frontend/components/Features";
import Slides from "@/../../../../WebstormProjects/Trade-frontend/components/Slides";
import Footer from "@/../../../../WebstormProjects/Trade-frontend/components/Footer";
import AboutUs from "@/components/AboutUs";

export default function Home() {

  return (
    <>
      <Head>
        <title>VOLUMENZEIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className=''>
          <FollowUs/>
          <MainContent/>
          <Features/>
          <OurMission/>
          <Slides/>
          <AboutUs/>
          <Footer/>
      </main>
    </>
  )
}
