import Head from 'next/head'
import AboutUs from "@/components/AboutUs";
import FollowUs from "@/components/FollowUs";
import MainContent from "@/components/MainContent";
import Features from "@/components/Features";
import OurMission from "@/components/OurMission";
import Slides from "@/components/Slides";
import Footer from "@/components/Footer";

export default function Home() {

  return (
    <>
      <Head>
        <title>VOLUMENZEIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='pt-[14px]'>
          <FollowUs/>
          <MainContent/>
          <Features/>
          <OurMission/>
          <Slides/>
          <AboutUs/>
          <Footer/>
      </main>
    </>
  )
}
